apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kuard-daemonset
  name: kuard-daemonset
spec:
  selector:
    matchLabels:
      k8s-app: kuard
  template:
    metadata:
      labels:
        k8s-app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
